/* Laylak Beauty Lounge — concept app data (fictional business, demo only). */
(function () {
  'use strict';

  var categories = [
    { id: 'hair',   en: 'Hair',   ar: 'الشعر',   long: { en: 'Hair', ar: 'الشعر' } },
    { id: 'nails',  en: 'Nails',  ar: 'الأظافر', long: { en: 'Nails', ar: 'الأظافر' } },
    { id: 'makeup', en: 'Makeup', ar: 'المكياج', long: { en: 'Makeup', ar: 'المكياج' } },
    { id: 'spa',    en: 'Spa',    ar: 'السبا',   long: { en: 'Spa & skin', ar: 'السبا والبشرة' } },
    { id: 'brows',  en: 'Brows',  ar: 'الحواجب', long: { en: 'Brows & lashes', ar: 'الحواجب والرموش' } }
  ];

  var notes = {
    hair: [
      { en: 'Please arrive with hair free of styling products.', ar: 'يُرجى الحضور بشعر خالٍ من منتجات التصفيف.' },
      { en: 'Ladies-only salon with private styling suites.', ar: 'صالون نسائي مع غرف تصفيف خاصة.' }
    ],
    nails: [
      { en: 'Every tool is sterilised after each guest.', ar: 'نعقّم جميع الأدوات بعد كل عميلة.' },
      { en: 'Have a design in mind? Bring a photo along.', ar: 'لديك تصميم معيّن؟ أحضري صورته معك.' }
    ],
    makeup: [
      { en: 'Arrive with clean, moisturised skin.', ar: 'يُفضّل الحضور ببشرة نظيفة ومرطّبة.' },
      { en: 'Tell us about your outfit and we will match the look.', ar: 'أخبرينا عن إطلالتك ولون فستانك لننسّق المكياج معهما.' }
    ],
    spa: [
      { en: 'Arrive 10 minutes early to relax with Arabic coffee.', ar: 'احضري قبل موعدك بعشر دقائق لتستمتعي بفنجان قهوة عربية.' },
      { en: 'Private rooms and fresh robes for every guest.', ar: 'غرف خاصة وأرواب نظيفة لكل عميلة.' }
    ],
    brows: [
      { en: 'Avoid tweezing your brows for two weeks before.', ar: 'تجنّبي نتف الحواجب قبل الموعد بأسبوعين.' },
      { en: 'A patch test is available on request.', ar: 'يمكن إجراء اختبار حساسية عند الطلب.' }
    ]
  };

  /* motif = illustration, bg = illustration backdrop */
  var services = [
    { id: 'blowdry', cat: 'hair', dur: 45, price: 8, popular: true, motif: 'dryer', bg: 'blush',
      en: 'Signature Blow-dry', ar: 'سشوار وتصفيف مميّز',
      d: { en: 'A smooth, long-lasting blow-dry finished with our lightweight shine mist for glossy movement that lasts for days.',
           ar: 'سشوار ناعم يدوم طويلًا، نختمه برذاذ اللمعان الخفيف لشعر مفعم بالحيوية والبريق لأيام.' },
      addons: ['scalp', 'mask'] },
    { id: 'cut', cat: 'hair', dur: 60, price: 15, motif: 'scissors', bg: 'cream',
      en: 'Haircut & Style', ar: 'قص وتصفيف الشعر',
      d: { en: 'A consultation-led cut tailored to your face shape and hair texture, finished with a blow-dry.',
           ar: 'قصّة مصمّمة لتناسب شكل وجهك وطبيعة شعرك بعد استشارة شخصية، مع سشوار في الختام.' },
      addons: ['mask', 'scalp'] },
    { id: 'colour', cat: 'hair', dur: 150, price: 45, motif: 'swatch', bg: 'peach',
      en: 'Full Hair Colour', ar: 'صبغة شعر كاملة',
      d: { en: 'Rich, even colour from roots to ends using ammonia-free formulas, sealed with a gloss for extra shine.',
           ar: 'لون غني ومتجانس من الجذور حتى الأطراف بتركيبات خالية من الأمونيا، مع لمسة غلوس لبريق إضافي.' },
      addons: ['bond', 'gloss'] },
    { id: 'keratin', cat: 'hair', dur: 180, price: 65, motif: 'wave', bg: 'lilac',
      en: 'Keratin Smoothing', ar: 'كيراتين لتنعيم الشعر',
      d: { en: 'Tames frizz for up to four months, perfect for humid Kuwaiti summers. Formaldehyde-free.',
           ar: 'يقضي على الهيشان والتموّج لمدة تصل إلى أربعة أشهر، ومثالي لرطوبة الصيف في الكويت. خالٍ من الفورمالديهايد.' },
      addons: ['mask', 'trim'] },
    { id: 'hairspa', cat: 'hair', dur: 60, price: 18, motif: 'oil', bg: 'sage',
      en: 'Argan Oil Hair Ritual', ar: 'حمّام زيت الأرغان للشعر',
      d: { en: 'A warm argan-oil treatment with steam and a relaxing scalp massage to restore softness and shine.',
           ar: 'علاج دافئ بزيت الأرغان مع البخار وتدليك مريح لفروة الرأس، يعيد لشعرك نعومته ولمعانه.' },
      addons: ['blowfinish'] },

    { id: 'mani', cat: 'nails', dur: 30, price: 6.5, motif: 'polish', bg: 'blush', tone: 'pink',
      en: 'Classic Manicure', ar: 'مناكير كلاسيكي',
      d: { en: 'Shaping, cuticle care and a hand massage, finished with the polish shade of your choice.',
           ar: 'تشكيل الأظافر والعناية بالجلد المحيط بها مع تدليك لليدين، وطلاء باللون الذي تختارينه.' },
      addons: ['french', 'paraffin'] },
    { id: 'gel', cat: 'nails', dur: 45, price: 9.5, popular: true, motif: 'polish', bg: 'lilac', tone: 'red', variant: 'gel',
      en: 'Gel Manicure', ar: 'مناكير جل',
      d: { en: 'Chip-free, high-gloss colour that lasts up to three weeks, with gentle cuticle care.',
           ar: 'لون لامع مقاوم للتقشّر يدوم حتى ثلاثة أسابيع، مع عناية لطيفة بالجلد المحيط بالأظافر.' },
      addons: ['french', 'accent', 'removal'] },
    { id: 'pedi', cat: 'nails', dur: 60, price: 12, motif: 'basin', bg: 'peach',
      en: 'Spa Pedicure', ar: 'باديكير سبا',
      d: { en: 'A warm rose-petal soak, gentle scrub, mask and massage, finished with polish.',
           ar: 'نقع القدمين في ماء دافئ مع بتلات الورد، ثم تقشير لطيف وماسك وتدليك، مع طلاء الأظافر في الختام.' },
      addons: ['gelup', 'paraffin'] },
    { id: 'nailart', cat: 'nails', dur: 75, price: 16, motif: 'gems', bg: 'plum',
      en: 'Nail Art Set', ar: 'رسم فني على الأظافر',
      d: { en: 'A gel manicure with hand-painted designs, chrome or crystal accents. Bring your inspiration.',
           ar: 'مناكير جل مع رسومات يدوية أو لمسات كروم أو كريستال. أحضري الصورة التي تلهمك ونصمّمها لك.' },
      addons: ['chrome', 'removal'] },

    { id: 'soiree', cat: 'makeup', dur: 60, price: 35, popular: true, motif: 'lipstick', bg: 'blush',
      en: 'Soirée Makeup', ar: 'مكياج سهرة',
      d: { en: 'Full evening glam that lasts all night: skin prep, contour, eyes and lashes included.',
           ar: 'إطلالة سهرة متكاملة تدوم طوال الليل، تشمل تحضير البشرة والكونتور ومكياج العيون والرموش.' },
      addons: ['updo', 'lashes'] },
    { id: 'natural', cat: 'makeup', dur: 45, price: 22, motif: 'palette', bg: 'peach',
      en: 'Natural Day Glow', ar: 'مكياج ناعم للنهار',
      d: { en: 'Fresh, radiant skin and soft definition, ideal for daytime occasions and photos.',
           ar: 'بشرة نضرة مشرقة وملامح ناعمة، مثالي للمناسبات النهارية والتصوير.' },
      addons: ['lashes'] },
    { id: 'bridal', cat: 'makeup', dur: 120, price: 120, motif: 'pearls', bg: 'lilac',
      en: 'Bridal Makeup', ar: 'مكياج العروس',
      d: { en: 'Your wedding look, perfected: a trial consultation, long-wear makeup and a lash fitting on the day.',
           ar: 'إطلالة ليلة العمر بأدق التفاصيل: جلسة تجربة واستشارة، ومكياج ثابت يدوم طويلًا، وتركيب رموش يوم الزفاف.' },
      addons: ['bridalhair', 'lashes'] },

    { id: 'hammam', cat: 'spa', dur: 75, price: 25, popular: true, motif: 'bowl', bg: 'cream',
      en: 'Moroccan Bath', ar: 'حمّام مغربي',
      d: { en: 'A traditional black-soap steam ritual and kessa scrub, followed by a rhassoul clay wrap.',
           ar: 'طقس تقليدي بالصابون الأسود والبخار والتقشير بالليفة المغربية، يليه لفّ الجسم بطين الغاسول.' },
      addons: ['roseoil', 'blowfinish'] },
    { id: 'facial', cat: 'spa', dur: 60, price: 28, popular: true, motif: 'serum', bg: 'blush',
      en: 'Hydrating Facial', ar: 'تنظيف البشرة بالترطيب العميق',
      d: { en: 'Deep cleansing, gentle exfoliation and a hyaluronic mask for plump, dewy skin.',
           ar: 'تنظيف عميق وتقشير لطيف، مع ماسك الهيالورونيك لبشرة ممتلئة ونضرة.' },
      addons: ['eyemask', 'led'] },
    { id: 'massage', cat: 'spa', dur: 60, price: 30, motif: 'stones', bg: 'sage', lead: 'dalal',
      en: 'Hot Stone Massage', ar: 'مساج بالأحجار الساخنة',
      d: { en: 'Warm basalt stones melt away tension in the back, neck and shoulders.',
           ar: 'أحجار بازلتية دافئة تذيب التوتر من الظهر والرقبة والكتفين.' },
      addons: ['aroma', 'extend'] },

    { id: 'threading', cat: 'brows', dur: 20, price: 4.5, motif: 'eye', bg: 'cream', variant: 'thread',
      en: 'Brow Shaping', ar: 'تحديد الحواجب بالخيط',
      d: { en: 'Precise threading to shape and define your natural arch.',
           ar: 'تحديد دقيق بالخيط يرسم القوس الطبيعي لحاجبيك.' },
      addons: ['tint', 'lip'] },
    { id: 'lamination', cat: 'brows', dur: 45, price: 15, motif: 'eye', bg: 'peach', variant: 'spoolie',
      en: 'Brow Lamination', ar: 'لامينيشن الحواجب',
      d: { en: 'Brushed-up, fuller-looking brows that stay set for up to six weeks.',
           ar: 'حواجب مرفوعة تبدو أكثف وأكثر ترتيبًا، وتثبت حتى ستة أسابيع.' },
      addons: ['tint'] },
    { id: 'lashlift', cat: 'brows', dur: 60, price: 18, popular: true, motif: 'eye', bg: 'lilac', variant: 'lash',
      en: 'Lash Lift & Tint', ar: 'رفع الرموش وصبغها',
      d: { en: 'Lifts and darkens your natural lashes for a wide-awake look, no extensions needed.',
           ar: 'يرفع رموشك الطبيعية ويمنحها لونًا أغمق لعيون مشرقة، من دون الحاجة إلى رموش صناعية.' },
      addons: ['browshape'] },
    { id: 'henna', cat: 'brows', dur: 40, price: 10, motif: 'cone', bg: 'blush',
      en: 'Henna Brows', ar: 'حنّاء الحواجب',
      d: { en: 'Plant-based henna tints both hairs and skin for soft, defined brows that last up to two weeks.',
           ar: 'حنّاء نباتية تلوّن الشعر والبشرة معًا لحواجب ناعمة ومحدّدة تدوم حتى أسبوعين.' },
      addons: ['lip'] }
  ];

  var addons = {
    scalp:      { min: 15, price: 3,   en: 'Scalp massage', ar: 'تدليك فروة الرأس' },
    mask:       { min: 15, price: 5,   en: 'Deep-conditioning mask', ar: 'ماسك ترطيب عميق للشعر' },
    bond:       { min: 20, price: 8,   en: 'Bond-repair treatment', ar: 'علاج لإصلاح روابط الشعر' },
    gloss:      { min: 15, price: 6,   en: 'Toner & gloss', ar: 'تونر وغلوس للمعان' },
    trim:       { min: 20, price: 4,   en: 'Ends trim', ar: 'قص الأطراف' },
    blowfinish: { min: 30, price: 5,   en: 'Blow-dry finish', ar: 'سشوار في الختام' },
    french:     { min: 10, price: 2.5, en: 'French tips', ar: 'رسمة فرنش' },
    paraffin:   { min: 15, price: 4,   en: 'Paraffin treatment', ar: 'علاج بشمع البارافين' },
    accent:     { min: 15, price: 3.5, en: 'Nail-art accent (2 nails)', ar: 'رسمة فنية على ظفرين' },
    removal:    { min: 10, price: 2,   en: 'Removal of old gel', ar: 'إزالة الجل السابق' },
    gelup:      { min: 10, price: 3,   en: 'Gel polish upgrade', ar: 'الترقية إلى طلاء جل' },
    chrome:     { min: 10, price: 3,   en: 'Chrome finish', ar: 'لمسة كروم' },
    updo:       { min: 45, price: 15,  en: 'Hair up-do', ar: 'تسريحة شعر مرفوعة' },
    lashes:     { min: 5,  price: 5,   en: 'Premium lashes', ar: 'رموش فاخرة' },
    bridalhair: { min: 60, price: 40,  en: 'Bridal hair styling', ar: 'تسريحة العروس' },
    roseoil:    { min: 20, price: 6,   en: 'Rose-oil body massage', ar: 'تدليك الجسم بزيت الورد' },
    eyemask:    { min: 10, price: 4,   en: 'Gold eye mask', ar: 'ماسك ذهبي لمحيط العين' },
    led:        { min: 15, price: 7,   en: 'LED light therapy', ar: 'جلسة العلاج بالضوء LED' },
    aroma:      { min: 0,  price: 3,   en: 'Aromatherapy oils', ar: 'زيوت عطرية علاجية' },
    extend:     { min: 30, price: 12,  en: 'Extra 30 minutes', ar: '30 دقيقة إضافية' },
    tint:       { min: 10, price: 3,   en: 'Brow tint', ar: 'صبغة الحواجب' },
    lip:        { min: 5,  price: 1.5, en: 'Upper-lip threading', ar: 'إزالة شعر الشفة العليا بالخيط' },
    browshape:  { min: 20, price: 4.5, en: 'Brow shaping', ar: 'تحديد الحواجب' }
  };

  /* Illustrated team (fictional people). Ratings are illustrative stars only. */
  var specialists = [
    { id: 'noura',  cats: ['hair'],            rating: 4.9, en: 'Noura',  ar: 'نورة',
      role: { en: 'Senior hair stylist', ar: 'مصفّفة شعر أولى' }, langs: { en: 'Arabic · English', ar: 'العربية · الإنجليزية' },
      look: { style: 'hijab', skin: '#E8B996', hair: '#5E2556', outfit: '#F3D9CF', bg: ['#F6E3EE', '#E7C9DD'] } },
    { id: 'reem',   cats: ['hair'],            rating: 4.8, en: 'Reem',   ar: 'ريم',
      role: { en: 'Colour specialist', ar: 'خبيرة صبغات الشعر' }, langs: { en: 'Arabic · English', ar: 'العربية · الإنجليزية' },
      look: { style: 'long', skin: '#F1C9A9', hair: '#4A2A1C', outfit: '#6E2D63', bg: ['#FCE6DE', '#F4C9BC'] } },
    { id: 'joanna', cats: ['nails'],           rating: 4.9, en: 'Joanna', ar: 'جوانا',
      role: { en: 'Nail artist', ar: 'فنّانة أظافر' }, langs: { en: 'English · Tagalog', ar: 'الإنجليزية · التاغالوغية' },
      look: { style: 'bun', skin: '#D9A27E', hair: '#22161B', outfit: '#E9A9A6', bg: ['#EFE6F8', '#D8C6EC'] } },
    { id: 'grace',  cats: ['nails'],           rating: 4.7, en: 'Grace',  ar: 'غريس',
      role: { en: 'Nail technician', ar: 'أخصائية أظافر' }, langs: { en: 'English · Tagalog', ar: 'الإنجليزية · التاغالوغية' },
      look: { style: 'pony', skin: '#C98E6B', hair: '#2B1A14', outfit: '#C7B2E0', bg: ['#FDEEE2', '#F5D3BA'] } },
    { id: 'hala',   cats: ['makeup', 'brows'], rating: 5.0, en: 'Hala',   ar: 'هلا',
      role: { en: 'Makeup artist', ar: 'خبيرة مكياج' }, langs: { en: 'Arabic · English · French', ar: 'العربية · الإنجليزية · الفرنسية' },
      look: { style: 'bob', skin: '#F2CDB0', hair: '#8A3E26', outfit: '#3E1638', bg: ['#FBE4E4', '#F1C2C6'] } },
    { id: 'lina',   cats: ['brows', 'makeup'], rating: 4.8, en: 'Lina',   ar: 'لينا',
      role: { en: 'Brow & lash expert', ar: 'خبيرة الحواجب والرموش' }, langs: { en: 'Arabic · English', ar: 'العربية · الإنجليزية' },
      look: { style: 'curly', skin: '#B97A57', hair: '#2E1A12', outfit: '#E7B4A0', bg: ['#EEF3EA', '#D3E0CD'] } },
    { id: 'mariam', cats: ['spa'],             rating: 4.9, en: 'Mariam', ar: 'مريم',
      role: { en: 'Spa therapist', ar: 'أخصائية سبا' }, langs: { en: 'Arabic · English', ar: 'العربية · الإنجليزية' },
      look: { style: 'hijab', skin: '#F0C4A2', hair: '#C98A73', outfit: '#FFF4EE', bg: ['#FDEFE6', '#F2D4C2'] } },
    { id: 'dalal',  cats: ['spa'],             rating: 4.8, en: 'Dalal',  ar: 'دلال',
      role: { en: 'Spa & massage therapist', ar: 'أخصائية سبا ومساج' }, langs: { en: 'Arabic · English', ar: 'العربية · الإنجليزية' },
      look: { style: 'hijab', skin: '#D8A584', hair: '#6F8F72', outfit: '#F6E7DA', bg: ['#EAF1E6', '#CFDEC8'] } }
  ];

  var promos = {
    HELLO15: { pct: 15 },
    GLOW20:  { pct: 20, services: ['facial'], days: [0, 1, 2, 3] }
  };

  var offers = [
    { id: 'o1', theme: 'plum', go: '/services', code: 'HELLO15',
      tag: { en: 'Welcome offer', ar: 'عرض الترحيب' },
      title: { en: '15% off your first visit', ar: 'خصم 15% على زيارتك الأولى' },
      sub: { en: 'Use code HELLO15 when you book', ar: 'استخدمي الرمز HELLO15 عند الحجز' } },
    { id: 'o2', theme: 'blush', go: '/service/facial', code: 'GLOW20',
      tag: { en: 'Midweek glow', ar: 'إشراقة منتصف الأسبوع' },
      title: { en: '20% off our hydrating facial', ar: 'خصم 20% على جلسة الترطيب العميق' },
      sub: { en: 'Sunday to Wednesday · code GLOW20', ar: 'من الأحد إلى الأربعاء · الرمز GLOW20' } },
    { id: 'o3', theme: 'lilac', go: '/service/bridal',
      tag: { en: 'Wedding season', ar: 'موسم الأعراس' },
      title: { en: 'Bridal trial session included', ar: 'جلسة تجربة مجانية للعروس' },
      sub: { en: 'Book your big-day look early', ar: 'احجزي إطلالة يومك الكبير مبكرًا' } }
  ];

  var S = {
    en: {
      appName: 'Laylak Beauty Lounge', brand: 'Laylak', brandSub: 'Beauty Lounge',
      metaTitle: 'Laylak Beauty Lounge — salon booking app (concept by Q8Pixel)',
      concept: 'Concept project by Q8Pixel',
      demoFoot: 'Laylak Beauty Lounge is a fictional salon created by Q8Pixel as a demo. It is not a real business: no bookings are made and nothing you enter leaves this device.',
      tabHome: 'Home', tabServices: 'Services', tabBookings: 'Bookings', tabProfile: 'Profile', mainNav: 'Main',
      back: 'Back', close: 'Close', skip: 'Skip', next: 'Next', getStarted: 'Get started',
      ob: [
        { t: 'Beauty, booked in seconds', p: 'Pick a service, choose your specialist and find a time that suits you, all in a few taps.' },
        { t: 'Your favourite specialist, every visit', p: 'See each specialist’s speciality and next free slot before you book.' },
        { t: 'Gentle reminders, easy changes', p: 'Get a reminder before every visit, and reschedule or cancel in a single tap.' }
      ],
      obNote: 'Concept app by Q8Pixel · Laylak is a fictional salon',
      slideOf: 'Slide {n} of {m}',
      gMorning: 'Good morning,', gAfternoon: 'Good afternoon,', gEvening: 'Good evening,',
      defaultName: 'Dana', homeSub: 'How shall we pamper you today?',
      searchPh: 'Search services, e.g. gel or blow-dry', searchLabel: 'Search services',
      categories: 'Categories', seeAll: 'See all', nextVisit: 'Your next visit', offers: 'Offers for you',
      popular: 'Popular right now', team: 'Meet the team', location: 'Salmiya', salonLoc: 'Salmiya, salon location and hours',
      notifs: 'Notifications', notifEmpty: 'You’re all caught up. No new notifications.',
      offerCta: 'Book now', offerOf: 'Offer {n} of {m}',
      services: 'Services', all: 'All', svcCount: '{n} services',
      bookNow: 'Book now', addons: 'Add-ons', addonsHint: 'Optional extras to tailor your visit',
      goodToKnow: 'Good to know', total: 'Total', fav: 'Save to favourites', favOn: 'Saved to favourites', favOff: 'Removed from favourites',
      specCount: '{n} specialists',
      chooseSpec: 'Choose specialist', step: 'Step {n} of 3', forSvc: 'For {s}',
      anySpec: 'Any specialist', anySpecSub: 'We’ll match you with the earliest available',
      firstFree: 'first available', yourBooking: 'Your booking', specTip: 'You can reschedule or cancel for free later in My bookings.',
      nextAvail: 'Next available', fullyBooked: 'Fully booked for two weeks', continue: 'Continue', rated: 'Rated {r} out of 5',
      pickTime: 'Date & time', pickTimeLead: 'Pick a day, then a time', today: 'Today', tomorrow: 'Tomorrow', tomorrowShort: '',
      morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening',
      noSlots: 'No times left on this day. Please try another date.', fridayNote: 'On Fridays we open at 2:00 PM.',
      unavailable: 'unavailable', withSpec: 'with {s}', selectTime: 'Select a time',
      review: 'Review & confirm', date: 'Date', time: 'Time', specialist: 'Specialist', duration: 'Duration', location2: 'Location', change: 'Change',
      salonShort: 'Laylak Beauty Lounge, Salmiya',
      yourDetails: 'Your details', fullName: 'Full name', mobile: 'Mobile number', mobileHint: '8 digits. Used for your booking confirmation (demo).',
      notes: 'Notes for your specialist (optional)', notesPh: 'e.g. allergies, inspiration, a shade you love',
      promo: 'Promo code', promoPh: 'Enter code', apply: 'Apply', remove: 'Remove',
      promoOk: '{code} applied: {pct}% off', promoBad: 'This code isn’t valid. Try HELLO15.', promoEmpty: 'Enter a code first.',
      promoGlow: 'GLOW20 is for the hydrating facial booked Sunday to Wednesday.',
      promoGone: '{code} doesn’t apply to the new date, so it was removed.',
      payment: 'Payment', paySalon: 'Pay at the salon', paySalonSub: 'Cash or card on the day', payKnet: 'KNET', payKnetSub: 'Demo only, no payment taken', payApple: 'Apple Pay', payAppleSub: 'Demo only, no payment taken',
      payNote: 'Prototype: no payment is taken and nothing is sent anywhere.',
      subtotal: 'Subtotal', discount: 'Discount', policy: 'Free cancellation up to 4 hours before your appointment.',
      confirm: 'Confirm booking · {p}', confirming: 'Confirming…',
      errName: 'Please enter your name.', errNameShort: 'Please enter at least 2 letters.',
      errPhone: 'Please enter your mobile number.', errPhoneBad: 'Enter an 8-digit Kuwaiti mobile number starting with 4, 5, 6 or 9.',
      fixErrors: 'Please check the highlighted fields.',
      booked: 'You’re booked!', bookedSub: 'See you {day}, {name}. Your appointment is saved in My bookings.',
      onDay: 'on {d}', bookingRef: 'Booking ref.', addCal: 'Add to calendar',
      calToast: 'Demo: the real app would add this visit to your calendar.',
      viewBookings: 'View my bookings', backHome: 'Back to home',
      myBookings: 'My bookings', upcoming: 'Upcoming', past: 'Past & cancelled', upcomingSr: ', {n} upcoming',
      current: 'Current', currentTime: 'current time', currently: 'Currently {w}',
      stUp: 'Confirmed', stDone: 'Completed', stCancel: 'Cancelled',
      reschedule: 'Reschedule', cancel: 'Cancel', bookAgain: 'Book again', directions: 'Directions',
      emptyUp: 'No upcoming visits', emptyUpSub: 'Treat yourself. Your next glow is only a few taps away.',
      emptyPast: 'No past visits yet', emptyPastSub: 'Your completed and cancelled visits will appear here.',
      browse: 'Browse services',
      suggestTitle: 'Ready for your next glow?', suggestSub: 'Our most-loved treatments are a tap away.',
      cancelTitle: 'Cancel this appointment?', cancelBody: 'Cancelling is free up to 4 hours before your visit, and you can always book again.',
      cancelYes: 'Yes, cancel it', keep: 'Keep my appointment', cancelled: 'Appointment cancelled.',
      reschedTitle: 'Choose a new time', reschedConfirm: 'Confirm new time', rescheduled: 'Moved to {w}.',
      profile: 'Profile', pearlClub: 'Laylak Pearl Club', points: '{n} points', nextReward: '60 points to a complimentary blow-dry',
      memberCard: 'Member card',
      account: 'Account', editDetails: 'Your details', addMobile: 'Add your mobile number', memberLine: 'Pearl Club member',
      language: 'Language', notifications: 'Notifications',
      nRemind: 'Appointment reminders', nRemindSub: 'A reminder 24 hours before each visit',
      nOffers: 'Offers & new services', nOffersSub: 'No more than twice a month',
      nSms: 'SMS updates', nSmsSub: 'Booking changes by text message',
      nToast: 'Demo: notification settings are simulated.',
      salon: 'Salon', salonInfo: 'Salon info & opening hours', contact: 'Contact the salon',
      contactToast: 'Demo only: in the real app this opens a chat with the salon.',
      install: 'Add to Home Screen', installSub: 'Use Laylak like a native app',
      demo: 'Demo', reset: 'Reset demo data', resetSub: 'Restore the sample bookings and settings',
      resetTitle: 'Reset the demo?', resetBody: 'Your test bookings, details and settings will return to the starting demo state.',
      resetYes: 'Reset demo', resetDone: 'Demo data reset.',
      about: 'About this concept', aboutSub: 'Designed & built by Q8Pixel', version: 'Version 1.0 · concept',
      address: 'Block 3, Salem Al Mubarak Street, Salmiya, Kuwait', hours: 'Opening hours',
      satThu: 'Saturday – Thursday', satThuH: '10:00 AM – 10:00 PM', fri: 'Friday', friH: '2:00 PM – 10:00 PM',
      salonPerks: 'Ladies-only · Private suites · Valet parking', call: 'Call the salon',
      demoToast: 'Demo only: this is a concept app, nothing was sent.',
      save: 'Save details', saved: 'Details saved.',
      installTitle: 'Install Laylak', installLead: 'Laylak runs full-screen from your home screen, just like an app from the store.',
      iosSteps: ['On iPhone, tap the Share button in Safari.', 'Choose “Add to Home Screen”.', 'Tap “Add”. Laylak opens full-screen like a native app.'],
      androidStep: 'On Android, open the browser menu (⋮) and choose “Install app”.',
      installNow: 'Install now', gotIt: 'Got it',
      search: 'Search', popularSearches: 'Popular searches', noResults: 'No services match “{q}”.', noResultsSub: 'Try “nails”, “facial” or “brows”.',
      clear: 'Clear',
      in: 'In {n} days',
      demoLink: 'Learn about Q8Pixel →',
      pitchTag: 'Q8Pixel concept', pitchTitle: 'Want an app like this for your salon?', pitchBody: 'Q8Pixel designs and builds real iPhone & Android booking apps for Kuwaiti businesses.', pitchCta: 'Talk to Q8Pixel',
      intro: {
        eyebrow: 'Concept app · by Q8Pixel',
        title: 'Clickable app prototype — try booking an appointment',
        tryIt: 'Jump straight in:',
        jumps: ['Book a gel manicure', 'My bookings'],
        qr: 'Scan to open it on your phone', qrAlt: 'QR code that opens this prototype on your phone',
        lead: 'Laylak Beauty Lounge is an invented Kuwaiti salon. Tap through the phone to book a service, pick a specialist and manage appointments, in English or Arabic.',
        b: [
          'Book in under a minute: service, specialist, date and time',
          'Full Arabic & English with a true right-to-left layout',
          'My bookings: reschedule or cancel in a tap, saved on the device',
          'Installable: add it to your home screen like a real app'
        ],
        note: 'Q8Pixel builds this as a real iPhone & Android app, with online payments, SMS reminders and a staff dashboard for your salon.',
        cta: 'Start your app with Q8Pixel',
        tip: 'Best on a phone: open this page on mobile to use it full-screen.',
        foot: 'Demo only: Laylak Beauty Lounge is not a real business. No bookings are made and no data is sent.'
      },
      langName: 'English', switchTo: 'العربية', switchLabel: 'Switch to Arabic'
    },

    ar: {
      appName: 'ليلك بيوتي لاونج', brand: 'ليلك', brandSub: 'بيوتي لاونج',
      metaTitle: 'ليلك بيوتي لاونج — تطبيق حجز مواعيد صالون (مشروع تجريبي من Q8Pixel)',
      concept: 'مشروع تجريبي من Q8Pixel',
      demoFoot: '«ليلك بيوتي لاونج» صالون خيالي صمّمته Q8Pixel كنموذج تجريبي، وليس نشاطًا تجاريًا حقيقيًا؛ لا تُسجَّل أي حجوزات فعلية، ولا تغادر بياناتك هذا الجهاز.',
      tabHome: 'الرئيسية', tabServices: 'الخدمات', tabBookings: 'حجوزاتي', tabProfile: 'حسابي', mainNav: 'التنقل الرئيسي',
      back: 'رجوع', close: 'إغلاق', skip: 'تخطّي', next: 'التالي', getStarted: 'لنبدأ',
      ob: [
        { t: 'احجزي موعد جمالك في ثوانٍ', p: 'اختاري الخدمة والخبيرة والوقت الذي يناسبك، كل ذلك ببضع لمسات.' },
        { t: 'خبيرتك المفضّلة في كل زيارة', p: 'اطّلعي على تخصّص كل خبيرة وأقرب موعد متاح لها قبل أن تحجزي.' },
        { t: 'تذكير لطيف وتعديل بسهولة', p: 'يصلك تذكير قبل كل موعد، ويمكنك تغيير الموعد أو إلغاؤه بلمسة واحدة.' }
      ],
      obNote: 'تطبيق تجريبي من Q8Pixel · «ليلك» صالون من نسج الخيال',
      slideOf: 'الشريحة {n} من {m}',
      gMorning: 'صباح الخير،', gAfternoon: 'مساء الخير،', gEvening: 'مساء الخير،',
      defaultName: 'دانة', homeSub: 'بماذا نُدلّلك اليوم؟',
      searchPh: 'ابحثي عن خدمة، مثل: جل أو سشوار', searchLabel: 'البحث عن الخدمات',
      categories: 'الأقسام', seeAll: 'عرض الكل', nextVisit: 'موعدك القادم', offers: 'عروض لكِ',
      popular: 'الأكثر طلبًا', team: 'تعرّفي على فريقنا', location: 'السالمية', salonLoc: 'السالمية، موقع الصالون وساعات العمل',
      notifs: 'الإشعارات', notifEmpty: 'لا توجد إشعارات جديدة.',
      offerCta: 'احجزي الآن', offerOf: 'العرض {n} من {m}',
      services: 'الخدمات', all: 'الكل', svcCount: '{n} خدمات',
      bookNow: 'احجزي الآن', addons: 'إضافات', addonsHint: 'خيارات اختيارية لتخصيص زيارتك',
      goodToKnow: 'معلومات تهمّك', total: 'الإجمالي', fav: 'حفظ في المفضّلة', favOn: 'أُضيفت إلى المفضّلة', favOff: 'أُزيلت من المفضّلة',
      specCount: '{n} خبيرات',
      chooseSpec: 'اختاري الخبيرة', step: 'الخطوة {n} من 3', forSvc: 'لخدمة {s}',
      anySpec: 'أي خبيرة متاحة', anySpecSub: 'سنحجز لكِ مع أول خبيرة متاحة',
      firstFree: 'أول خبيرة متاحة', yourBooking: 'حجزك', specTip: 'يمكنك تغيير الموعد أو إلغاؤه مجانًا لاحقًا من «حجوزاتي».',
      nextAvail: 'أقرب موعد', fullyBooked: 'محجوزة بالكامل لأسبوعين', continue: 'متابعة', rated: 'التقييم {r} من 5',
      pickTime: 'التاريخ والوقت', pickTimeLead: 'اختاري اليوم ثم الوقت', today: 'اليوم', tomorrow: 'غدًا', tomorrowShort: 'غدًا',
      morning: 'الصباح', afternoon: 'بعد الظهر', evening: 'المساء',
      noSlots: 'لا توجد أوقات متاحة في هذا اليوم، جرّبي يومًا آخر.', fridayNote: 'نفتح أيام الجمعة الساعة 2:00 ظهرًا.',
      unavailable: 'غير متاح', withSpec: 'مع {s}', selectTime: 'اختاري الوقت',
      review: 'مراجعة وتأكيد', date: 'التاريخ', time: 'الوقت', specialist: 'الخبيرة', duration: 'المدة', location2: 'الموقع', change: 'تعديل',
      salonShort: 'ليلك بيوتي لاونج، السالمية',
      yourDetails: 'بياناتك', fullName: 'الاسم الكامل', mobile: 'رقم الهاتف المحمول', mobileHint: '8 أرقام، لتأكيد الحجز (تجريبي).',
      notes: 'ملاحظات للخبيرة (اختياري)', notesPh: 'مثل: حساسية معيّنة، أو صورة ملهمة، أو لون تحبّينه',
      promo: 'رمز الخصم', promoPh: 'أدخلي الرمز', apply: 'تطبيق', remove: 'إزالة',
      promoOk: 'تم تطبيق {code}: خصم {pct}%', promoBad: 'هذا الرمز غير صالح. جرّبي HELLO15.', promoEmpty: 'أدخلي رمز الخصم أولًا.',
      promoGlow: 'رمز GLOW20 مخصّص لجلسة الترطيب العميق من الأحد إلى الأربعاء.',
      promoGone: 'لم يعد الرمز {code} صالحًا للموعد الجديد، لذا أُزيل.',
      payment: 'طريقة الدفع', paySalon: 'الدفع في الصالون', paySalonSub: 'نقدًا أو بالبطاقة يوم الموعد', payKnet: 'كي نت', payKnetSub: 'تجريبي، لن يُخصم أي مبلغ', payApple: 'Apple Pay', payAppleSub: 'تجريبي، لن يُخصم أي مبلغ',
      payNote: 'نموذج تجريبي: لن يُخصم أي مبلغ ولن تُرسَل أي بيانات.',
      subtotal: 'المجموع الفرعي', discount: 'الخصم', policy: 'الإلغاء مجاني حتى 4 ساعات قبل موعدك.',
      confirm: 'تأكيد الحجز · {p}', confirming: 'جارٍ التأكيد…',
      errName: 'يُرجى إدخال اسمك.', errNameShort: 'يُرجى إدخال حرفين على الأقل.',
      errPhone: 'يُرجى إدخال رقم هاتفك المحمول.', errPhoneBad: 'أدخلي رقمًا كويتيًا من 8 أرقام يبدأ بـ 4 أو 5 أو 6 أو 9.',
      fixErrors: 'يُرجى مراجعة الحقول المشار إليها.',
      booked: 'تم تأكيد حجزك!', bookedSub: 'نراكِ {day} يا {name}. تجدين موعدك في «حجوزاتي».',
      onDay: 'يوم {d}', bookingRef: 'رقم الحجز', addCal: 'إضافة إلى التقويم',
      calToast: 'تجريبي: في التطبيق الفعلي يُضاف الموعد إلى تقويمك.',
      viewBookings: 'عرض حجوزاتي', backHome: 'العودة إلى الرئيسية',
      myBookings: 'حجوزاتي', upcoming: 'القادمة', past: 'السابقة والملغاة', upcomingSr: '، مواعيد قادمة: {n}',
      current: 'الحالي', currentTime: 'الموعد الحالي', currently: 'الموعد الحالي: {w}',
      stUp: 'مؤكَّد', stDone: 'مكتمل', stCancel: 'ملغى',
      reschedule: 'تغيير الموعد', cancel: 'إلغاء', bookAgain: 'احجزي مجددًا', directions: 'الاتجاهات',
      emptyUp: 'لا توجد مواعيد قادمة', emptyUpSub: 'دلّلي نفسك، فإطلالتك القادمة على بُعد لمسات.',
      emptyPast: 'لا توجد زيارات سابقة بعد', emptyPastSub: 'ستظهر هنا زياراتك المكتملة والملغاة.',
      browse: 'تصفّحي الخدمات',
      suggestTitle: 'مستعدة لإطلالتك القادمة؟', suggestSub: 'أكثر جلساتنا طلبًا على بُعد لمسة.',
      cancelTitle: 'هل تريدين إلغاء هذا الموعد؟', cancelBody: 'الإلغاء مجاني حتى 4 ساعات قبل الموعد، ويمكنك الحجز مجددًا في أي وقت.',
      cancelYes: 'نعم، إلغاء الموعد', keep: 'الإبقاء على الموعد', cancelled: 'تم إلغاء الموعد.',
      reschedTitle: 'اختاري موعدًا جديدًا', reschedConfirm: 'تأكيد الموعد الجديد', rescheduled: 'تم تغيير الموعد إلى {w}.',
      profile: 'حسابي', pearlClub: 'نادي لؤلؤة ليلك', points: '{n} نقطة', nextReward: 'تبقّت لكِ 60 نقطة للحصول على سشوار مجاني',
      memberCard: 'بطاقة العضوية',
      account: 'الحساب', editDetails: 'بياناتك الشخصية', addMobile: 'أضيفي رقم هاتفك', memberLine: 'عضوة في نادي لؤلؤة ليلك',
      language: 'اللغة', notifications: 'الإشعارات',
      nRemind: 'تذكير بالمواعيد', nRemindSub: 'تذكير قبل كل موعد بـ 24 ساعة',
      nOffers: 'العروض والخدمات الجديدة', nOffersSub: 'مرتان في الشهر كحدٍّ أقصى',
      nSms: 'تحديثات بالرسائل النصية', nSmsSub: 'إشعار بأي تغيير في مواعيدك',
      nToast: 'تجريبي: إعدادات الإشعارات هنا للعرض فقط.',
      salon: 'الصالون', salonInfo: 'معلومات الصالون وساعات العمل', contact: 'تواصلي مع الصالون',
      contactToast: 'تجريبي فقط: في التطبيق الفعلي يفتح هذا محادثة مع الصالون.',
      install: 'إضافة إلى الشاشة الرئيسية', installSub: 'استخدمي «ليلك» كأي تطبيق على جوالك',
      demo: 'النسخة التجريبية', reset: 'إعادة ضبط البيانات التجريبية', resetSub: 'استعادة الحجوزات والإعدادات النموذجية',
      resetTitle: 'إعادة ضبط النسخة التجريبية؟', resetBody: 'ستعود حجوزاتك وبياناتك وإعداداتك التجريبية إلى حالتها الأولى.',
      resetYes: 'إعادة الضبط', resetDone: 'تمت إعادة ضبط البيانات.',
      about: 'عن هذا المشروع التجريبي', aboutSub: 'من تصميم وتطوير Q8Pixel', version: 'الإصدار 1.0 · نسخة تجريبية',
      address: 'قطعة 3، شارع سالم المبارك، السالمية، الكويت', hours: 'ساعات العمل',
      satThu: 'السبت – الخميس', satThuH: '10:00 ص – 10:00 م', fri: 'الجمعة', friH: '2:00 م – 10:00 م',
      salonPerks: 'صالون نسائي · غرف خاصة · خدمة صفّ السيارات', call: 'اتصلي بنا',
      demoToast: 'تجريبي فقط: هذا تطبيق نموذجي ولم يُرسَل أي شيء.',
      save: 'حفظ البيانات', saved: 'تم حفظ بياناتك.',
      installTitle: 'ثبّتي تطبيق ليلك', installLead: 'يعمل «ليلك» بملء الشاشة من الشاشة الرئيسية تمامًا كتطبيقات المتجر.',
      iosSteps: ['على iPhone، اضغطي زر المشاركة في متصفح سفاري.', 'اختاري «إضافة إلى الشاشة الرئيسية».', 'اضغطي «إضافة»، وسيفتح «ليلك» بملء الشاشة كأي تطبيق.'],
      androidStep: 'على أندرويد، افتحي قائمة المتصفح (⋮) واختاري «تثبيت التطبيق».',
      installNow: 'التثبيت الآن', gotIt: 'حسنًا',
      search: 'البحث', popularSearches: 'عمليات بحث شائعة', noResults: 'لا توجد خدمات تطابق «{q}».', noResultsSub: 'جرّبي «أظافر» أو «بشرة» أو «حواجب».',
      clear: 'مسح',
      in: 'بعد {n} أيام',
      demoLink: 'تعرّف على Q8Pixel ←',
      pitchTag: 'مشروع تجريبي من Q8Pixel', pitchTitle: 'هل تريد تطبيقًا كهذا لصالونك؟', pitchBody: 'تصمّم Q8Pixel وتطوّر تطبيقات حجز حقيقية لأجهزة iPhone وAndroid للأنشطة التجارية في الكويت.', pitchCta: 'تواصل مع Q8Pixel',
      intro: {
        eyebrow: 'تطبيق تجريبي · من Q8Pixel',
        title: 'نموذج تطبيق تفاعلي — جرّب حجز موعد',
        tryIt: 'ابدأ التجربة مباشرةً:',
        jumps: ['احجز مناكير جل', 'حجوزاتي'],
        qr: 'امسح الرمز لفتحه على هاتفك', qrAlt: 'رمز QR يفتح هذا النموذج على هاتفك',
        lead: '«ليلك بيوتي لاونج» صالون كويتي من نسج الخيال. تنقّل داخل الهاتف لحجز خدمة واختيار الخبيرة وإدارة المواعيد، بالعربية أو الإنجليزية.',
        b: [
          'حجز في أقل من دقيقة: الخدمة والخبيرة واليوم والوقت',
          'دعم كامل للعربية والإنجليزية مع واجهة تنعكس من اليمين إلى اليسار',
          '«حجوزاتي»: تغيير الموعد أو إلغاؤه بلمسة، مع حفظ البيانات على الجهاز',
          'قابل للتثبيت: أضِفه إلى الشاشة الرئيسية كأي تطبيق حقيقي'
        ],
        note: 'تُطوِّر Q8Pixel هذا النموذج ليصبح تطبيقًا حقيقيًا لأجهزة iPhone وAndroid، مع الدفع الإلكتروني وتذكير المواعيد بالرسائل النصية ولوحة تحكّم لفريق صالونك.',
        cta: 'ابدأ تطبيقك مع Q8Pixel',
        tip: 'التجربة الأفضل على الجوال: افتح هذه الصفحة من هاتفك لتستخدم التطبيق بملء الشاشة.',
        foot: 'نموذج تجريبي: «ليلك بيوتي لاونج» ليس نشاطًا تجاريًا حقيقيًا، ولا تُسجَّل أي حجوزات ولا تُرسَل أي بيانات.'
      },
      langName: 'العربية', switchTo: 'English', switchLabel: 'التبديل إلى الإنجليزية'
    }
  };

  var days = {
    en: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    enS: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    ar: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
    arS: ['أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'سبت']
  };
  var months = {
    en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    enS: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    ar: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر']
  };

  var popularSearches = ['gel', 'blowdry', 'hammam', 'lashlift', 'bridal'];

  window.LAYLAK_DATA = {
    categories: categories, notes: notes, services: services, addons: addons,
    specialists: specialists, promos: promos, offers: offers, S: S, days: days, months: months,
    popularSearches: popularSearches
  };
})();
